theme = "dracula"

[editor]
line-number = "relative"
mouse = false
true-color = true
text-width = 80

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
right = ["diagnostics", "total-line-numbers", "selections", "position"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-w" = ":buffer-close"
"A-/" = "repeat_last_motion"

[keys.insert]
j = { k = "normal_mode" }
